# python train_net.py --config-file configs/semantic/train_semantic_base.yaml  --num-gpus 8 

_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  META_ARCHITECTURE: "MAFT_Plus"  # FCCLIP MAFT_Plus
  SEM_SEG_HEAD:
    NAME: "FCCLIPHead"
    NUM_CLASSES: 171
  FC_CLIP:
    CLIP_MODEL_NAME: "convnext_base_w_320"  
    CLIP_PRETRAINED_WEIGHTS: "laion_aesthetic_s13b_b82k_augreg"   
    EMBED_DIM: 640
    GEOMETRIC_ENSEMBLE_ALPHA: -1.
    GEOMETRIC_ENSEMBLE_BETA: -1.
  rc_weights: 0.1
  cdt_params:
  - 640
  - 8

INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic" # mask_former_semantic coco_panoptic_lsj
DATASETS:
  TRAIN: ("openvocab_coco_2017_train_stuff_sem_seg",)  
  TEST: ("openvocab_ade20k_full_sem_seg_val", 'openvocab_ade20k_panoptic_val') 

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  MAX_ITER: 60000

OUTPUT_DIR: ./out/semantic/MAFT_Plus_base/ori
     